name: CI
on:
  push:
    branches:
      - main
jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@v1
        with:
          python-version: 3.6
          architecture: 'x64'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Check codestyle
        run: pycodestyle ./shop/*.py
      - name: Tests
        run: python manage.py test